server:
  port: 0  # Port will be assigned automatically

spring:
  application:
    name: eclient

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

logging:
  pattern:
    console: "%C{1.} [%5level] %d{HH:mm:ss} - %msg%n"
